//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_EmpresaLINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGO_EMPLEADO
    {
        public int idCargo_empleado { get; set; }
        public int idEmpleado { get; set; }
        public int idCargo { get; set; }
    
        public virtual CARGO CARGO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
    }
}
